In [1]:
import numpy as np

In [2]:
print(np.cos(np.pi))

-1.0


In [4]:
print(np.sqrt(1683746))

1297.5923859209408


In [5]:
print(np.exp(5.3))

200.33680997479166


In [11]:
vec = np.array([[1,2,3],[4,5,6],[7,8,9]])
vec

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
vec.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [15]:
vec2 = np.arange(0,15,2)
vec2

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [18]:
mat2 = np.ones([5,3])
mat2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
vec1 = np.arange(1,6)
vec1

array([1, 2, 3, 4, 5])

In [24]:
vec2 = np.arange(3,8)
vec2

array([3, 4, 5, 6, 7])

In [25]:
vec1+vec2

array([ 4,  6,  8, 10, 12])

In [26]:
vec1-vec2

array([-2, -2, -2, -2, -2])

In [27]:
vec1*vec2

array([ 3,  8, 15, 24, 35])

In [28]:
np.sqrt(vec2)

array([1.73205081, 2.        , 2.23606798, 2.44948974, 2.64575131])

In [30]:
a = np.array([1,2,2,3,3,3,3,3,3,4])
a

array([1, 2, 2, 3, 3, 3, 3, 3, 3, 4])

In [31]:
np.unique(a)

array([1, 2, 3, 4])

# Pandas

In [32]:
import pandas as pd

In [39]:
a = np.arange(21,26)
a

array([21, 22, 23, 24, 25])

In [48]:
my_label = ['first','second','third','fourth','fifth']
my_label = pd.Series(my_label)

In [46]:
b = pd.Series(data = a,)
b

0    21
1    22
2    23
3    24
4    25
dtype: int32

In [42]:
pd.Series(a, my_label)

first     21
second    22
third     23
fourth    24
fifth     25
dtype: int32

In [43]:
pd.Series([4,2,8,6,9],['a','b','c','d','e'])

a    4
b    2
c    8
d    6
e    9
dtype: int64

In [49]:
df = pd.concat([b, my_label], axis=1)

In [50]:
df

0       1
0  21   first
1  22  second
2  23   third
3  24  fourth
4  25   fifth

In [93]:
df = pd.DataFrame({'class':[1,2,6,7,8],
              'name':['ram','shyam','Geeta','Lala','kamla']
    
})
df 

class   name
0      1    ram
1      2  shyam
2      6  Geeta
3      7   Lala
4      8  kamla

In [94]:
df[['class','name']]

class   name
0      1    ram
1      2  shyam
2      6  Geeta
3      7   Lala
4      8  kamla

In [95]:
df.loc[2:3]

class   name
2      6  Geeta
3      7   Lala

In [96]:
df.iloc[2]

class        6
name     Geeta
Name: 2, dtype: object

In [97]:
df

class   name
0      1    ram
1      2  shyam
2      6  Geeta
3      7   Lala
4      8  kamla

In [98]:
df['Location'] = ['delhi','mumbai','Lucknow','Beng','Hydra']

In [99]:
df

class   name Location
0      1    ram    delhi
1      2  shyam   mumbai
2      6  Geeta  Lucknow
3      7   Lala     Beng
4      8  kamla    Hydra

In [100]:
# df = df.drop(['class'],axis=1)
# df

In [102]:
df

class   name Location
0      1    ram    delhi
1      2  shyam   mumbai
2      6  Geeta  Lucknow
3      7   Lala     Beng
4      8  kamla    Hydra

In [103]:
df.set_index('Location', inplace= True)

In [104]:
df

class   name
Location              
delhi         1    ram
mumbai        2  shyam
Lucknow       6  Geeta
Beng          7   Lala
Hydra         8  kamla

In [107]:
df.reset_index(inplace=True)

In [108]:
df

Location  class   name
0    delhi      1    ram
1   mumbai      2  shyam
2  Lucknow      6  Geeta
3     Beng      7   Lala
4    Hydra      8  kamla

In [109]:
#Concat, Join, merge

In [ ]:
left join
right join
inner join
full join


In [111]:
df1 = pd.DataFrame({'customer':[101,102,103,104],
                    'category':['cat2','cat2','cat1','cat3'],
                    'importance':['yes','no','yes','no']    
})
df1

customer category importance
0       101     cat2        yes
1       102     cat2         no
2       103     cat1        yes
3       104     cat3         no

In [113]:
df2 = pd.DataFrame({'customer':[101,103,104,105],
                    'color':['yellow','green','green','blue']
    
})
df2

customer   color
0       101  yellow
1       103   green
2       104   green
3       105    blue

In [115]:
pd.concat([df1,df2],axis =1)

customer category importance  customer   color
0       101     cat2        yes       101  yellow
1       102     cat2         no       103   green
2       103     cat1        yes       104   green
3       104     cat3         no       105    blue

In [116]:
pd.merge(df1,df2,how = 'right',on = 'customer')

customer category importance   color
0       101     cat2        yes  yellow
1       103     cat1        yes   green
2       104     cat3         no   green
3       105      NaN        NaN    blue

In [117]:
pd.merge(df1,df2,how = 'left',on = 'customer')

customer category importance   color
0       101     cat2        yes  yellow
1       102     cat2         no     NaN
2       103     cat1        yes   green
3       104     cat3         no   green

In [118]:
pd.merge(df1,df2,how = 'inner',on = 'customer')

customer category importance   color
0       101     cat2        yes  yellow
1       103     cat1        yes   green
2       104     cat3         no   green

In [119]:
pd.merge(df1,df2,how = 'outer',on = 'customer')

customer category importance   color
0       101     cat2        yes  yellow
1       102     cat2         no     NaN
2       103     cat1        yes   green
3       104     cat3         no   green
4       105      NaN        NaN    blue

In [128]:
df3 = pd.DataFrame({'Q1':[101,102,103],
                    'Q2':[201,202,203]},
                    index =['a','b','c']
    
)
df3

Q1   Q2
a  101  201
b  102  202
c  103  203

In [129]:
df4 = pd.DataFrame({'Q3':[301,302,303],
                    'Q4':[401,402,403]},
                    index =['a','b','d']
    
)
df4

Q3   Q4
a  301  401
b  302  402
d  303  403

In [135]:
final = df3.join(df4, how = 'outer')
final

Q1     Q2     Q3     Q4
a  101.0  201.0  301.0  401.0
b  102.0  202.0  302.0  402.0
c  103.0  203.0    NaN    NaN
d    NaN    NaN  303.0  403.0

In [136]:
final

Q1     Q2     Q3     Q4
a  101.0  201.0  301.0  401.0
b  102.0  202.0  302.0  402.0
c  103.0  203.0    NaN    NaN
d    NaN    NaN  303.0  403.0

In [141]:
final['Q1'].max()

103.0